version: "3.7"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/data"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: hangmandb
