# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "solargraph", "~> 0.39.11", :group => :development

gem "sinatra", "~> 2.0"
gem "puma", "~> 4.3"

gem "sequel", "~> 5.34"

gem "pg", "~> 1.2"
